# vim:ft=toml
live_config_reload = true

[colors.bright]
black = "#6f737c"
blue = "#9fd5ff"
cyan = "#d2ebff"
green = "#c5ef86"
magenta = "#deb7f8"
red = "#ff84a0"
white = "#e9ebf0"
yellow = "#f9dcb3"

[colors.normal]
black = "#1f2430"
blue = "#6cbeff"
cyan = "#9fd4ff"
green = "#addb67"
magenta = "#c792ea"
red = "#f45c7f"
white = "#e9ebf0"
yellow = "#ecc48d"

[colors.primary]
background = "#1f2430"
foreground = "#e9ebf0"

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "P"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "Y"
mods = "Alt"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "zsh"

[window]
decorations = "none"
startup_mode = "Windowed"
