#!/bin/bash

if [ "$1" == '-d' ]; then
  sudo rm -rf /nix ~/.nix-channels ~/.nix-defexpr ~/.nix-profile ~/.local/state/nix/
elif ! command -v nix &>/dev/null; then
  # install nix
  curl -L https://nixos.org/nix/install | sh -s -- --no-daemon

  # install home-manager
  nix-channel --add https://github.com/nix-community/home-manager/archive/release-25.11.tar.gz home-manager
  nix-channel --update
  nix-shell '<home-manager>' -A install
fi
