#!/bin/bash

if command -v nix &>/dev/null; then
  # setup home-manager
  cd "$WORK_DIR"
  home-manager switch -b hm-bak --extra-experimental-features nix-command --extra-experimental-features flakes --extra-experimental-features pipe-operators --flake .
fi
