#!/bin/bash

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share

if [ "$1" == "-d" ]; then
  if command -v nix &>/dev/null; then
    cd "$WORK_DIR"
    sudo -E $(which nix) run github:numtide/system-manager -- deactivate
  fi

  for n in $(seq 1 10); do
    sudo userdel nixbld$n
  done
  sudo groupdel nixbld
else
  sudo groupadd -r nixbld || true
  for n in $(seq 1 10); do sudo useradd -c "Nix build user $n" \
    -d /var/empty -g nixbld -G nixbld -M -N -r -s "$(which nologin)" \
    nixbld$n; done

  if command -v nix &>/dev/null; then
    # run system manager
    cd "$WORK_DIR"
    sudo -E $(which nix) run github:numtide/system-manager -- switch --flake .
  fi
fi
