#!/bin/bash

set -e

OPTION=$1
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
export WORK_DIR="$SCRIPT_DIR/.."

cd $SCRIPT_DIR

export PATH="$PATH:$HOME/.nix-profile/bin"

./_install_nix $OPTION
./_run_home_manager $OPTION
./_run_system_manager $OPTION
./_install_xsessions_desktop $OPTION
./_build_output_folder $OPTION
./_set_user_permissions $OPTION
./_install_ubuntu_extras $OPTION
