[general]
live_config_reload = true

[colors.bright]
black = "{{ colors.grey4 }}"
blue = "{{ colors.blue | lighten }}"
cyan = "{{ colors.cyan | lighten }}"
green = "{{ colors.green | lighten }}"
magenta = "{{ colors.magenta | lighten }}"
red = "{{ colors.red | lighten }}"
white = "{{ colors.foreground }}"
yellow = "{{ colors.yellow | lighten }}"

[colors.normal]
black = "{{ colors.background }}"
blue = "{{ colors.blue }}"
cyan = "{{ colors.cyan }}"
green = "{{ colors.green }}"
magenta = "{{ colors.magenta }}"
red = "{{ colors.red }}"
white = "{{ colors.foreground }}"
yellow = "{{ colors.yellow }}"

[colors.primary]
background = "{{ colors.background }}"
foreground = "{{ colors.foreground }}"

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = {{ fontSize }}

[font.normal]
family = "{{ font }}"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "+"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "="
mods = "Control"

[terminal.shell]
program = "zsh"

[window]
decorations = "none"
startup_mode = "Windowed"

[hints]
alphabet = "arstgmneio"

[[hints.enabled]]
regex = "(/?(?:[\\w.-]+?/)*[\\w.-]+)(:(\\d+))+"
command = "run_on_nvim"
post_processing = true

[hints.enabled.binding]
key = "X"
mods = "Control|Shift"
