#!/bin/bash

SERVICE_LOCATION=/usr/share/xsessions/i3.desktop

if [ "$1" == "-d" ]; then
	sudo rm -f $SERVICE_LOCATION

	echo "Xsession entry unset"
else
	sudo tee $SERVICE_LOCATION 1>/dev/null <<EOF
[Desktop Entry]
Name=i3
Comment=i3
Exec=i3
Type=Application
X-LightDM-DesktopName=i3
DesktopNames=i3
Keywords=tiling
EOF

	echo "Xsession entry set"
fi
