#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

# install nix
curl -L https://nixos.org/nix/install | sh -s -- --no-daemon
PATH="$PATH:$HOME/.nix-profile/bin"

# install home-manager
nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
nix-channel --update
nix-shell '<home-manager>' -A install
rm -rf ~/.config/nix/nix.conf
mkdir -p ~/.config/nix/
cp -r "$SCRIPT_DIR/nix.conf" ~/.config/nix/nix.conf
