-- vim:ft=lua

local colors = {
  strong_blue = "#52b3ff",
  strong_green = "#aaff29",
  strong_red = "#ff3765",
  strong_yellow = "#ffbc60",
  dark_red = "#e03d63",
  red = "#f45c7f",
  light_red = "#ff84a0",
  dark_green = "#93bf50",
  green = "#addb67",
  light_green = "#c5ef86",
  dark_yellow = "#d7ab6f",
  yellow = "#ecc48d",
  light_yellow = "#f9dcb3",
  dark_blue = "#48a6f0",
  blue = "#6cbeff",
  light_blue = "#9fd5ff",
  dark_magenta = "#ae75d4",
  magenta = "#c792ea",
  light_magenta = "#deb7f8",
  dark_cyan = "#77bcf4",
  cyan = "#9fd4ff",
  light_cyan = "#d2ebff",
  background = "#1f2430",
  background_alt1 = "#191d27",
  background_alt2 = "#252b39",
  grey1 = "#333843",
  grey2 = "#474b56",
  grey3 = "#5b5f69",
  grey4 = "#6f737c",
  grey5 = "#83868f",
  grey6 = "#979aa2",
  grey7 = "#abaeb5",
  grey8 = "#bfc1c8",
  grey9 = "#d3d5db",
  foreground = "#e9ebf0",
}

local syntax = {
  statement = "#f78c6c",
  ["function"] = "#6cbeff",
  variable = "#e9ebf0",
  include = "#c792ea",
  keyword = "#c792ea",
  struct = "#f45c7f",
  string = "#addb67",
  identifier = "#9fd4ff",
  field = "#9fd4ff",
  parameter = "#f45c7f",
  property = "#f78c6c",
  punctuation = "#e9ebf0",
  constructor = "#9fd4ff",
  operator = "#bfc1c8",
  preproc = "#9fd4ff",
  constant = "#f78c6c",
  tag = "#f45c7f",
  todo = { fg = "#9fd4ff", bg = "#333843" },
  number = "#f78c6c",
  comment = "#6f737c",
  type = "#ecc48d",
  conditional = "#f45c7f",
}

local themer = {
  red = colors.dark_red,
  yellow = colors.yellow,
  orange = colors.dark_yellow,
  magenta = colors.magenta,
  blue = colors.blue,
  green = colors.green,
  cyan = colors.cyan,

  directory = colors.blue,
  fg = colors.foreground,
  diff = {
    add = colors.dark_green,
    remove = colors.dark_red,
    text = colors.dark_blue,
    change = colors.dark_yellow,
  },
  accent = colors.cyan,
  search_result = { fg = colors.background_alt1, bg = colors.blue, telescope = colors.blue },
  match = colors.grey9,
  dimmed = { bg = colors.grey4, fg = colors.grey4 },
  bg = {
    base = colors.background,
    alt = colors.background_alt2,
    selected = colors.grey2,
  },
  border = colors.foreground,
  syntax = syntax,
  built_in = syntax,
  diagnostic = {
    error = colors.strong_red,
    warn = colors.strong_yellow,
    info = colors.strong_green,
    hint = colors.magenta,
  },
  inc_search = { fg = colors.background_alt1, bg = colors.blue },
  uri = colors.dark_yellow,
  pum = {
    fg = colors.grey9,
    bg = colors.background_alt1,
    sbar = colors.background_alt2,
    thumb = colors.blue,
    sel = { bg = colors.grey2, fg = colors.foreground },
  },
  heading = {
    h1 = colors.blue,
    h2 = colors.blue,
  },
  remaps = {
    base = {
      WinSeparator = { fg = colors.grey2, bg = colors.background },
      DiffAdd = { fg = colors.dark_green, bg = colors.background },
      DiffChange = { fg = colors.dark_yellow, bg = colors.background },
      DiffDelete = { fg = colors.dark_red, bg = colors.background },
    },
    plugins = {
      nvim_tree = {
        NVimTreeNormal = { fg = colors.foreground, bg = colors.background_alt1 },
        NvimTreeGitDeleted = { fg = colors.red },
        NvimTreeGitDirty = { fg = colors.yellow },
        NvimTreeGitStaged = { fg = colors.green },
        NvimTreeGitMerge = { fg = colors.yellow },
        NvimTreeGitNew = { fg = colors.red },
        NvimTreeGitRenamed = { fg = colors.foreground },
        NvimTreeSpecialFile = { fg = colors.foreground },
        NvimTreeImageFile = { fg = colors.foreground },
        NvimTreeOpenedFile = { fg = colors.foreground },
        NvimTreeModifiedFile = { fg = colors.foreground },
        NvimTreeIndentMarker = { fg = colors.foreground },
        NvimTreeSymlink = { fg = colors.foreground },
        NvimTreeExecFile = { fg = colors.foreground },
      },
      microscope = {
        MicroscopeMatch = { fg = colors.blue },
        MicroscopeColor1 = { fg = colors.red },
        MicroscopeColor2 = { fg = colors.green },
      },
    },
  },
}

local lualine = {
  normal = {
    a = { fg = colors.background, bg = colors.green, gui = "bold" },
    b = { fg = colors.foreground, bg = colors.grey3 },
    c = { fg = colors.foreground, bg = colors.background_alt2 },
  },
  command = { a = { fg = colors.background, bg = colors.yellow, gui = "bold" } },
  insert = { a = { fg = colors.background, bg = colors.blue, gui = "bold" } },
  visual = { a = { fg = colors.background, bg = colors.magenta, gui = "bold" } },
  terminal = { a = { fg = colors.background, bg = colors.cyan, gui = "bold" } },
  replace = { a = { fg = colors.background, bg = colors.red, gui = "bold" } },
}

return {
  themer = themer,
  lualine = lualine,
}
