#!/usr/bin/env python

import glob
import os
import rofi_menu
import sys

themes_path = os.path.dirname(os.path.realpath(sys.argv[0])) + "/../theme/"


class Themes(rofi_menu.Menu):
    prompt = "menu"

    def __init__(self, themes=[]):
        self.items = map(self._gen, themes)

    def _gen(self, theme):
        return rofi_menu.ShellItem(theme, "set_theme " + theme)


if __name__ == "__main__":
    os.chdir(themes_path)
    files = glob.glob("*.json")

    themes = list(map(lambda x: x.replace(".json", ""), files))
    themes.sort()

    rofi_menu.run(Themes(themes))
