#!/bin/env bash

case $1 in
all)
	systemctl --user restart dunst polybar picom
	i3-msg restart >/dev/null || true
	;;
dunst) systemctl --user restart dunst ;;
polybar) systemctl --user restart polybar ;;
picom) systemctl --user restart picom ;;
i3) i3-msg restart >/dev/null || true ;;
*) echo "Invalid $1" ;;
esac
