#!/bin/env bash

DOTS_PATH="$(dirname "$(readlink -f "$0")")/.."
THEME_STORAGE="$HOME/.dots_theme"
DEFAULT_THEME="aylin"

cd "$DOTS_PATH"

if [[ -n "$1" ]]; then
	if ! [[ -f "$DOTS_PATH/theme/$1.json" ]]; then
		echo "Invalid theme $1"
		exit 1
	fi
	theme=$1
elif [[ -f "$THEME_STORAGE" ]]; then
	theme=$(cat "$THEME_STORAGE")
else
	theme=$DEFAULT_THEME
fi

echo $theme >"$THEME_STORAGE"

node templating/index.js $theme || exit 1

systemctl --user restart dunst polybar picom
i3-msg reload >/dev/null || true
