#!/bin/bash

# Thanks to https://github.com/NixOS/nixpkgs/issues/158025#issuecomment-1616807870

SERVICE="install-unix_chkpwd-wrapper.service"
SERVICE_LOCATION="/lib/systemd/system/$SERVICE"
MOUNT_POINT="/run/wrappers"

if [ "$1" == "-d" ]; then
  if sudo mountpoint -q $MOUNT_POINT; then
    sudo umount $MOUNT_POINT
  fi
  sudo rm -rf $MOUNT_POINT
  sudo systemctl disable $SERVICE
  sudo rm $SERVICE_LOCATION

  echo "Run wrappers unset"
elif [ -f "$SERVICE_LOCATION" ]; then
  sudo mkdir -p $MOUNT_POINT
  sudo mountpoint -q $MOUNT_POINT || sudo mount -t tmpfs -o defaults,nodev,noatime,mode=755 tmpfs $MOUNT_POINT
  sudo tee $SERVICE_LOCATION 1>/dev/null <<EOF
[Unit]
After=run-wrappers.mount
Wants=run-wrappers.mount

[Service]
Type=oneshot
ExecStart=/usr/bin/mkdir -p $MOUNT_POINT/bin
ExecStart=/usr/bin/ln -sf /sbin/unix_chkpwd $MOUNT_POINT/bin/unix_chkpwd

[Install]
WantedBy=multi-user.target
EOF
  sudo systemctl enable $SERVICE

  echo "Run wrappers set"
fi
