#!/bin/bash

set -e

OPTION=$1
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

cd $SCRIPT_DIR

export PATH="$PATH:$HOME/.nix-profile/bin"

./_install_nix $OPTION
./_run_home_manager $OPTION
./_install_xsessions_desktop $OPTION
./_set_pam $OPTION
./_set_zsh $OPTION
./_build_output_folder $OPTION
